### ISSUE TITLE
Node version 

### ISSUE THREAD

**Issue by sprynm** [straker/gulp-livingcss#15]
Appears my PR failed due to Node 0.12 requirement (https://github.com/straker/gulp-livingcss/blob/master/.travis.yml).  This conflicts with mocha that's even planning to drop v4 support soon (https://github.com/mochajs/mocha/issues/3149).

Any reason this version must be maintained?

**Comment by straker** [comment]
Nope, just out of date since last created. Feel free to upgrade to latest active Node version. Thanks the pr btw.

**Comment by straker** [comment]
Closing with #14. Thanks again.
