### ISSUE TITLE
Racing condition when using gulp-livingcss on multiple stylus files?

### ISSUE THREAD

**Issue by phun-ky** [straker/gulp-livingcss#17]
I'm getting this error:

    [14:20:05] { [Error: section 'Components.Modal' is not defined (/project/packages/dialog/src/dialog.styl:11)]
      message: 'section \'Components.Modal\' is not defined (/project/packages/dialog/src/dialog.styl:11)',
      plugin: 'gulp-livingcss',
      showProperties: true,
      showStack: false,
      __safety: { toString: [Function: bound ] } }

With this code:

    const generateStyleGuide = () =>
      gulp
        .src([
          './packages/core/src/core.styl',
          './packages/typography/src/typography.styl',
          './packages/icons/src/icons.styl',
          './packages/forms/src/forms.styl',
          './packages/breakpoints/src/breakpoints.styl',
          './packages/cards/src/cards.styl',
          './packages/buttons/src/buttons.styl',
          './packages/list/src/list.styl',
          './packages/tables/src/tables.styl',
          './packages/media/src/media.styl',
          './packages/modal/src/modal.styl',
          './packages/notifications/src/notifications.styl',
          './packages/grid/src/grid.styl',
          './packages/menu/src/menu.styl',
          './packages/global-header/src/global-header.styl',
          './packages/sliders/src/sliders.styl',
          './packages/panel/src/panel.styl',
          './packages/loader/src/loader.styl',
          './packages/pagination/src/pagination.styl',
          './packages/dialog/src/dialog.styl',
          './packages/timeline/src/timeline.styl',
          './packages/stepper/src/stepper.styl',
          './packages/expandable/src/expandable.styl',
          './packages/tooltip/src/tooltip.styl',
          './packages/badges/src/badges.styl',
          './packages/selection-controls/src/selection-controls.styl',
          './packages/text-field/src/text-field.styl',
          './packages/color/src/color.styl'
        ])
        .pipe(
          livingcss('bin', {
            template: './template/template.hbs',
            preprocess: (context, template, Handlebars) => {
              // register a glob of partials with Handlebars
              return livingcss.utils.readFileGlobs('./template/partials/*.hbs', function(data, file) {
                // make the name of the partial the name of the file
                const partialName = path.basename(file, path.extname(file));
                Handlebars.registerPartial(partialName, data);
              });
            }
          })
        )
        .on('error', log)
        .pipe(gulp.dest('bin'));

I get this from time to time, over one year now. For now I've restarted the script, but it is getting frustrating. Is there a racing condition here? `dialog.styl` is included way after `modal.styl`, so this should not be an issue tbh :(

    $ gulp -v
    [14:24:29] CLI version 2.0.1
    [14:24:29] Local version 4.0.0

    $ node -v
    v8.11.1

    $ npm -v
    6.2.0

    "gulp-livingcss": "^2.1.0",

Contents of `dialog.styl`:

    @require 'color.styl'
    @require 'icons.styl'
    @require 'typography.styl'
    @require 'buttons.styl'
    @require 'modal.styl'

    /**
     * @doc ../docs/dialog.md
     * @subrepo {IfInsurance/relax} relax-dialog - Dialog
     * @section
     * @sectionof Components.Modal
     */
    .dialog
      @extend .modal

Contents of `modal.styl`:

    @require 'color.styl'
    @require 'icons.styl'
    @require 'typography.styl'
    @require 'buttons.styl'

    /**
     * @repo {IfInsurance/relax} relax-modal - Modal
     * @doc ../docs/modal.md
     * @section
     * @sectionof Components
     */
    .modal

**Comment by straker** [comment]
Hu, the code should allow for sections to forward reference other sections, so even if the files were processed out of order it should still work.

Is your project somewhere public that I could download it and play with it? Since it's happening sporadically I'm thinking it might be hard for me to setup a test case on my end.

**Comment by phun-ky** [comment]
@straker one other thing I experience is that the sections generated are not in the same order each time I generate a new styleguide, could this be related? Or is it that the gulp stream src does not guarantee order when loading files?

And sadly, no, the project is not public :(

**Comment by straker** [comment]
I can't seem to find a definitive source on whether or not explicitly listing files guarantees order in `gulp.src` (I would assume they do). I tried to retain order of all files as they are read in my code, but it might be possible I messed up.

Try this: add `gulp-debug` to the pipe right before livingcss and note the order it returns to see if it changes. If it doesn't change but livingcss still changes the order of sections, then that would be a problem on my end for explicitly listed files. I can't guarantee any order for globs. 

Since the code isn't public, let me see if I can add verbose logging to see if we can find the problem.

**Comment by phun-ky** [comment]
Using `gulp-debug` proves that the file stream has the correct order of files. 

After some debugging, it is `livingcss` that throws the error. I also logged the complete error object, producing this:

    ReferenceError: section 'Components.Modal' is not defined (/project/packages/dialog/src/dialog.styl:11)
        at Object.sectionof (/project/node_modules/livingcss/lib/tags.js:161:16)
        at /project/node_modules/livingcss/lib/parseComments.js:72:23
        at Array.forEach (<anonymous>)
        at parseComments (/project/node_modules/livingcss/lib/parseComments.js:64:12)
        at /project/node_modules/livingcss/index.js:111:7
        at /project/node_modules/livingcss/lib/utils.js:190:16
        at Array.forEach (<anonymous>)
        at /project/node_modules/livingcss/lib/utils.js:189:11
        at <anonymous>
    [07:31:57] { [Error: section 'Components.Modal' is not defined (/project/packages/dialog/src/dialog.styl:11)]
      message: 'section \'Components.Modal\' is not defined (/project/packages/dialog/src/dialog.styl:11)',
      plugin: 'gulp-livingcss',
      showProperties: true,
      showStack: false,
      __safety: { toString: [Function: bound ] } }

Will keep on digging

**Comment by phun-ky** [comment]
I tried to log something from the `// forward referenced section` in `livingcss/lib/tags:161`, and I see that you always store a `ReferenceError` for each forwarded section, is this intended?

Because this:

    // forward referenced section
    else {
      console.log('#############################')
      console.log(JSON.stringify(this.tag,null, 2))
      console.log(JSON.stringify(this.block,null, 2))
      console.log('#############################')
      forwardReferenceSections[this.tag.description] = forwardReferenceSections[this.tag.description] || [];
      forwardReferenceSections[this.tag.description].push({
        block: this.block,

        // save error so we have line number, file, and correct location
        error: new ReferenceError('section \'' + this.tag.description +
          '\' is not defined (' + this.file + ':' + (this.tag.line+1) + ')')
      });
    }

Produces this for a component that has never been thrown an error for (no error thrown, just output): (`description` field omitted for brevity)

    #############################
    {
      "tag": "sectionof",
      "description": "Style",
      "optional": false,
      "type": "",
      "name": "",
      "line": 3,
      "source": "@sectionof Style"
    }
    {
      "name": "Typography",
      "description": "...",
      "id": "style-typography",
      "depth": 2,
      "isSection": true,
      "parent": "Style"
    }
    #############################
    #############################
    {
      "tag": "sectionof",
      "description": "Style",
      "optional": false,
      "type": "",
      "name": "",
      "line": 14,
      "source": "@sectionof Style\n"
    }
    {
      "repo": {
        "description": "Icons",
        "name": "relax-icons",
        "type": "IfInsurance/relax"
      },
      "name": "Icons",
      "description": "...",
      "id": "style-icons",
      "depth": 2,
      "isSection": true,
      "parent": "Style"
    }
    #############################

**EDIT:** I see now that this is produced for many components on second run, but on the first run, I only got the first two as described above

**EDIT 2:** I think I get it now, since the output of the console.log commands is varying in size, you use the forward reference section to try to catch the forward reference issues right?

**Comment by phun-ky** [comment]
With this code:

    if (section) {
      section.children = section.children || [];
      section.children.push(this.block);
      if(this.block.name === 'Dialog' || this.block.name === 'Modal'){
      console.log('#############################')
      console.log(JSON.stringify(this.block,null, 2))
      console.log('#############################')}
    }

    // forward referenced section
    else {

      forwardReferenceSections[this.tag.description] = forwardReferenceSections[this.tag.description] || [];
      forwardReferenceSections[this.tag.description].push({
        block: this.block,

        // save error so we have line number, file, and correct location
        error: new ReferenceError('section \'' + this.tag.description +
          '\' is not defined (' + this.file + ':' + (this.tag.line+1) + ')')
      });
      if(this.block.name === 'Dialog' || this.block.name === 'Modal'){
      console.log('#############################')
      console.log(JSON.stringify(forwardReferenceSections,null, 2))
      console.log('#############################')}
    }

On a successful run:

    #############################
    {
      "repo": {
        "description": "Modal",
        "name": "relax-modal",
      },
      "name": "Modal",
      "description": "...",
      "id": "components-modal",
      "depth": 2,
      "isSection": true,
      "parent": "Components"
    }
    #############################
    #############################
    {
      "subrepo": {
        "description": "Dialog",
        "name": "relax-dialog",
      },
      "name": "Dialog",
      "description": "...",
      "id": "components-modal-dialog",
      "depth": 3,
      "isSection": true,
      "parent": "Components.Modal"
    }
    #############################

Unsuccessful:

    #############################
    {
      "Components.Modal": [
        {
          "block": {
            "subrepo": {
              "description": "Dialog",
              "name": "relax-dialog",
            },
            "name": "Dialog",
            "description": "...",
            "id": "components-modal-dialog",
            "depth": 3,
            "isSection": true,
            "parent": "Components.Modal"
          },
          "error": {}
        }
      ]
    }
    #############################
    #############################
    {
      "repo": {
        "description": "Modal",
        "name": "relax-modal",
      },
      "name": "Modal",
      "description": "...",
      "id": "components-modal",
      "depth": 2,
      "isSection": true,
      "parent": "Components"
    }
    #############################
    ReferenceError: section 'Components.Modal' is not defined (/project/packages/dialog/src/dialog.styl:11)
        at Object.sectionof (/project/node_modules/livingcss/lib/tags.js:166:16)
        at /project/node_modules/livingcss/lib/parseComments.js:72:23
        at Array.forEach (<anonymous>)
        at parseComments (/project/node_modules/livingcss/lib/parseComments.js:64:12)
        at /project/node_modules/livingcss/index.js:111:7
        at /project/node_modules/livingcss/lib/utils.js:190:16
        at Array.forEach (<anonymous>)
        at /project/node_modules/livingcss/lib/utils.js:189:11
        at <anonymous>
    [07:59:03] { [Error: section 'Components.Modal' is not defined (/project/packages/dialog/src/dialog.styl:11)]
      message: 'section \'Components.Modal\' is not defined (/project/packages/dialog/src/dialog.styl:11)',
      plugin: 'gulp-livingcss',
      showProperties: true,
      showStack: false,
      __safety: { toString: [Function: bound ] } }

Seems like a type of racing condition here, or am I missing something?

**Comment by straker** [comment]
Thanks for all that logging. I'm glad `gulp.src` is giving files in order. It would seem that livingcss isn't maintaining that order, so I'll see if I can set up a test case that includes lots of files and see if I can debug the problem.

To answer your question about the error message. I can only throw an error for a missing section after I have processed all files, that way you can reference a section that would be defined later. But if I were to throw an error at that point in the code, I wouldn't have access to the comment block or file that tried to reference the missing section, so I figured it was easiest just to create an error object which saved all that information, and then throw later after all files have been processed.

So ya, if you're forward referencing sections there will be a lot of error messages that just get thrown out after the section has been found.

**Comment by phun-ky** [comment]
Hm, I see I've neglected to mention on which environment this occurs. This happens, if I remember correctly, exclusively on Windows 10, with Ubuntu Bash WSL. regardless of node-version. I can't remember that this has happened on my pure Ubuntu laptop.

**Comment by phun-ky** [comment]
We just added a CI build for our styleguide, and we now see the same error in our VSTS Build Pipeline :(

**Comment by straker** [comment]
Sorry for lack of update. I participated in the js13k game jam which just wrapped up so now should have time to work on this problem as my first priority.

**Comment by straker** [comment]
I just published a fix to livingcss that should fix the problem with files being read out of order. Let me know if that helps any.

**Comment by phun-ky** [comment]
I've tested it locally on windows 10 ubuntu bash with no more errors, but I witnessed it today in our CI-builds. The CI build _might_ have some cache, but I am confident that it doesn't. Will let you know if the problem persists.

One thing I noticed in the local builds, is that the component sections are now in the same order every time, and that's a plus!

**Comment by straker** [comment]
Awesome! Glad the sections are being ordered correctly.

**Comment by phun-ky** [comment]
Saw the same error locally again :(  windows 10 ubuntu bash

**Comment by straker** [comment]
Dang. 

Would it be possible to share the contents of both the doc files for the Dialog and Modal, as well as the Component doc/comment? If you want you can share it with me as a private gist instead of posting it here.

**Comment by phun-ky** [comment]
Sorry for late reply, but the section in order looks like a false positive. they are not in order. let me just run it by my organization about access, so it could be much easier!

**Comment by phun-ky** [comment]
Experiencing this daily now, in git bash (win 10), but in Ubuntu, I've never experienced this (perhaps 1 or 2 times, not nearly often enough for it to be an issue)

![bilde](https://user-images.githubusercontent.com/1714029/54339273-a90dac00-4634-11e9-93b1-ccf270854a14.png)


Toss me a PM so I can give you access to the repo @straker , when/if you have the time

**Comment by straker** [comment]
Oh shoot, I totally missed this message. Sorry about that. I have time to work on this now so if  you're still getting the error it'd be great to see what's causing it with repo access.

**Comment by straker** [comment]
Closed via https://github.com/straker/livingcss/pull/73
