### ISSUE TITLE
Can preprocessor be used to clean the css before template is compiled?

### ISSUE THREAD

**Issue by phun-ky** [straker/gulp-livingcss#20]
I'm trying to use the preprocess function to remove duplicates in the css, but the context.parsedStylesheets seems unchanged when using it. should this be an option in the package itself? I've made a PR about this, since this doesn't work in the gulpfile..

    preprocess: function(context, template, Handlebars) {
      return new Promise(function(resolve, reject) {
        var stylesheets = context.stylesheets.map(function(file) {
          return path.join(process.cwd(), 'bin' || '.', file);
        });

        livingcss.utils
          .readFiles(stylesheets, function(data) {
            context.parsedStylesheets = context.parsedStylesheets || [];
            context.parsedStylesheets.push(livingcss.utils.fixSVGIssue(data));
          })
          .then(function() {
            var allCSS = context.parsedStylesheets
              .map(function(stylesheet) {
                return stylesheet;
              })
              .join('\n');
            var allDedupedCSS = new CleanCSS({ level: 2 }).minify(allCSS);

            context.parsedStylesheets = [allDedupedCSS.styles];

            if (allDedupedCSS.errors.length !== 0) {
              reject(allDedupedCSS.errors.join('\n'));
            }
          })
          .then(function() {
            Handlebars.registerHelper('global', function(key) {
              return lernaCfg[key];
            });
            // register a glob of partials with Handlebars
            livingcss.utils
              .readFileGlobs('./template/partials/*.hbs', function(data, file) {
                // make the name of the partial the name of the file
                const partialName = path.basename(file, path.extname(file));
                Handlebars.registerPartial(partialName, data);
              })
              .then(function() {
                resolve();
              })
              .catch(function(e) {
                console.log(e);
                reject(e);
              });
          });
      });
    }

REF: https://github.com/straker/gulp-livingcss/pull/22

**Comment by straker** [comment]
Closed via #22
